### ISSUE TITLE
TOUT EST A FAIRE !!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by EmilienPapin** [bts-sio/generateurPL-emilien.guillaume#2]

**Comment by groolot** [comment]
c'est bien insuffisant de le dire tel quel.
Vous devez envisager ensemble de déterminer des groupes de tâches ou d'objectifs simples à atteindre.

Vous pourriez commencer par vous questionner sur :
 - comment fait-on un programme ?
 - quelles sont les étapes pour avoir un programme très simple et fonctionnel ?
 - etc.

une fois ces 'atomes' identifiés vous pourrez alors les organiser, les structurer.

**Comment by EmilienPapin** [comment]
Merci pour votre commentaire. Mais j'avais surtout généré cette issue afin d'en découvrir le fonctionnement. Les nouvelles issues seront bien évidemment plus précises.

**Comment by groolot** [comment]
ok.
alors tu peux déplacer l'issue dans la colonne 'Done' ou bien directement la clôturer dans GitHub.
